from __future__ import annotations

from dataclasses import dataclass
from html import escape
from typing import Iterable, Mapping


PORTAL_STORY_TITLES: dict[str, str] = {
    "task": "任务是什么",
    "decision": "系统怎么决定这样做",
    "execution": "实际怎么执行",
    "evidence": "拿到了哪些关键证据",
    "result": "最终结果是什么",
    "details": "还可以往下看什么细节",
}

_AUTOGENERATED_FIELD_LABELS = {
    "context_paths": "context 范围",
    "editable_paths": "可修改范围",
    "expected_changed_files": "预计改动文件",
    "behavioral_checks": "行为要求",
    "acceptance_checks": "验收标准",
}


@dataclass(frozen=True, slots=True)
class StoryDetail:
    title: str
    body_html: str


@dataclass(frozen=True, slots=True)
class StorySection:
    key: str
    title: str
    status: str
    headline: str
    bullets: tuple[str, ...]
    details: tuple[StoryDetail, ...] = ()


def build_portal_story_sections(
    *,
    preview: Mapping[str, object],
    form_fields: Mapping[str, str],
    mode: str,
    autogenerated_fields: Iterable[str],
    used_draft_verifier: bool,
    results: Iterable[Mapping[str, object]],
    links: Iterable[Mapping[str, object]],
    detail_blocks: Iterable[tuple[str, str]] = (),
    result_details_html: str = "",
) -> tuple[StorySection, ...]:
    task_preview = _mapping(preview.get("task_spec_preview"))
    shared_info = _mapping(preview.get("shared_task_information"))
    current_delivery = _mapping(preview.get("current_delivery"))
    uplift = _mapping(preview.get("uplift_readiness"))
    task_text = str(form_fields.get("task_text") or task_preview.get("description") or "").strip()
    repo_source = str(form_fields.get("repo_path") or task_preview.get("repo_root") or "").strip()
    autogenerated = tuple(_AUTOGENERATED_FIELD_LABELS.get(item, item) for item in autogenerated_fields if str(item).strip())
    context_files = _strings(current_delivery.get("context_files"))
    expected_files = _strings(task_preview.get("expected_changed_files"))
    editable_paths = _strings(task_preview.get("editable_paths"))
    behavioral_checks = _strings(task_preview.get("behavioral_checks"))
    verifier_steps = _strings(task_preview.get("verifier_step_names"))
    tree_preview = _strings(current_delivery.get("tree_preview"))
    additional_delivery_items = _strings(current_delivery.get("additional_delivery_items"))
    delivery_notes = _strings(current_delivery.get("notes"))
    risk_warnings = _strings(preview.get("risk_warnings"))
    recommendation_reasons = _strings(uplift.get("recommendation_reasons"))
    harness_signals = _strings(uplift.get("declared_harness_signals"))
    link_items = tuple(_normalized_links(links))
    result_items = tuple(_normalized_results(results))

    task_bullets = _bullets(
        (
            f"任务目标：{_truncate(task_text or str(task_preview.get('description') or ''), 90) or '还没写清楚'}",
            f"仓库来源：{repo_source or '还没填写'}",
            f"预计改动：{_join_items(expected_files, '还没限定目标文件')}",
            f"可修改范围：{_join_items(editable_paths, '未显式限制')}",
        )
    )
    decision_bullets = _bullets(
        (
            f"系统自动草拟：{_join_items(autogenerated, '没有自动补字段')}" if autogenerated else "",
            f"任务形态：{form_fields.get('task_shape') or task_preview.get('task_type') or 'general'}",
            f"材料包：{form_fields.get('knowledge_pack') or 'none'}",
            f"验收会看：{_join_items(verifier_steps[:3], '先看改动文件和行为要求')}",
            "验收方式：草稿完成度估算" if used_draft_verifier else "验收方式：真实 acceptance checks 或 verifier",
        )
    )
    environment = _mapping(shared_info.get("environment"))
    execution_bullets = _bullets(
        (
            "执行主线：先在隔离工作区副本里运行，再交给确定性 verifier；需要项目外结论时再接官方 scorer。",
            additional_delivery_items[0] if additional_delivery_items else "",
            additional_delivery_items[1] if len(additional_delivery_items) > 1 else "",
            delivery_notes[0] if delivery_notes else "",
            f"工作环境：{environment.get('repo_source_kind') or 'unknown'} / {environment.get('checkout_mode') or 'copy'}",
            "联网：允许" if bool(environment.get("allow_network")) else "联网：关闭",
        )
    )
    evidence_bullets = _bullets(
        (
            f"上下文文件：{_join_items(context_files[:3], '当前还没挑出上下文文件')}",
            (
                f"仓库树预览：已识别 {current_delivery.get('tree_file_count')} 个文件，首屏只取 {len(tree_preview)} 项"
                if current_delivery.get("tree_file_count") is not None
                else "仓库树预览：当前拿不到本地仓库结构"
            ),
            recommendation_reasons[0] if recommendation_reasons else "",
            f"Harness 信号：{_join_items(harness_signals, '暂时没有显式信号')}",
            risk_warnings[0] if risk_warnings else "",
        )
    )

    result_status = _result_status(result_items)
    result_headline = _result_headline(result_items, used_draft_verifier=used_draft_verifier)
    result_bullets = _result_bullets(result_items, used_draft_verifier=used_draft_verifier)
    detail_bullets = _bullets(
        (
            f"可直接打开：{_join_items([item['label'] for item in link_items], '运行报告、套件页、对比页会放这里')}",
            "原始 Prompt、完整 patch、完整 verifier 输出都放在折叠细节里。",
            "如果需要项目外统一结论，会从这里继续接官方 scorer 相关入口。",
            "最近任务也只保留一键回填入口，不把历史堆满首屏。",
        )
    )

    prompt_preview = _mapping(current_delivery.get("prompt_preview"))
    task_details = (
        StoryDetail(
            title="查看任务边界",
            body_html=_render_string_grid(
                (
                    ("任务标题", str(task_preview.get("title") or "未命名任务")),
                    ("仓库来源", repo_source or "未填写"),
                    ("预计改动", _join_items(expected_files, "还没限定目标文件")),
                    ("可修改范围", _join_items(editable_paths, "未显式限制")),
                    ("行为要求", _join_items(behavioral_checks, "未额外声明")),
                )
            ),
        ),
    )
    decision_details = (
        StoryDetail(
            title="查看系统草稿",
            body_html=_render_string_grid(
                (
                    ("task_shape", str(form_fields.get("task_shape") or task_preview.get("task_type") or "general")),
                    ("knowledge_pack", str(form_fields.get("knowledge_pack") or "none")),
                    ("context_paths", str(form_fields.get("context_paths_text") or "未填写")),
                    ("editable_paths", str(form_fields.get("editable_paths_text") or "未填写")),
                    ("behavioral_checks", str(form_fields.get("behavioral_checks_text") or "未填写")),
                    ("acceptance_checks", str(form_fields.get("acceptance_checks_text") or "未填写")),
                )
            ),
        ),
    )
    execution_details = _detail_items(
        (
            ("查看原始 Prompt", _render_prompt_blocks(prompt_preview)),
            ("查看上下文文件", _render_string_list(context_files, empty_text="当前还没选出上下文文件。")),
            ("查看仓库树预览", _render_string_list(tree_preview, empty_text="当前还没有仓库树预览。")),
        )
    )
    evidence_details = _detail_items(
        (
            ("查看风险提示", _render_string_list(risk_warnings, empty_text="当前没有额外风险提示。")),
            ("查看推荐理由", _render_string_list(recommendation_reasons, empty_text="当前没有推荐理由。")),
        )
    )
    result_details = _detail_items((("查看结果明细", result_details_html),) if result_details_html else ())
    detail_details = _detail_items(
        (
            ("查看跳转入口", _render_link_list(link_items)),
            *tuple((title, body_html) for title, body_html in detail_blocks if title and body_html),
        )
    )

    return (
        StorySection("task", PORTAL_STORY_TITLES["task"], "ready", _task_headline(task_preview, task_text), task_bullets, task_details),
        StorySection("decision", PORTAL_STORY_TITLES["decision"], "ready", _decision_headline(mode, autogenerated, used_draft_verifier), decision_bullets, decision_details),
        StorySection("execution", PORTAL_STORY_TITLES["execution"], "ready", _execution_headline(current_delivery), execution_bullets, execution_details),
        StorySection("evidence", PORTAL_STORY_TITLES["evidence"], "ready", _evidence_headline(context_files, risk_warnings), evidence_bullets, evidence_details),
        StorySection("result", PORTAL_STORY_TITLES["result"], result_status, result_headline, result_bullets, result_details),
        StorySection("details", PORTAL_STORY_TITLES["details"], "info", "首屏只讲结论，原始材料都在折叠区。", detail_bullets, detail_details),
    )


def render_portal_story(sections: Iterable[StorySection]) -> str:
    cards: list[str] = []
    for index, section in enumerate(sections, start=1):
        cards.append(
            "".join(
                [
                    f'<article class="story-card story-status-{escape(section.status)}" data-story-key="{escape(section.key)}">',
                    '<div class="story-head">',
                    f'<div class="story-step">{index:02d}</div>',
                    '<div class="story-copy">',
                    '<div class="story-title-row">',
                    f"<h3>{escape(section.title)}</h3>",
                    f'<span class="story-badge">{escape(_status_label(section.status))}</span>',
                    "</div>",
                    f'<p class="story-headline">{escape(section.headline)}</p>',
                    "</div>",
                    "</div>",
                    _render_string_list(section.bullets, empty_text="当前没有额外说明。", css_class="story-list"),
                    "".join(
                        f'<details class="story-detail"><summary>{escape(detail.title)}</summary><div class="story-detail-body">{detail.body_html}</div></details>'
                        for detail in section.details
                    ),
                    "</article>",
                ]
            )
        )
    return '<div class="story-stack">' + "".join(cards) + "</div>"


def _normalized_results(results: Iterable[Mapping[str, object]]) -> tuple[dict[str, str], ...]:
    normalized: list[dict[str, str]] = []
    for item in results:
        if not isinstance(item, Mapping):
            continue
        normalized.append(
            {
                "profile_label": str(item.get("profile_label") or item.get("profile") or "current"),
                "status": str(item.get("status") or "pending"),
                "status_label": str(item.get("status_label") or item.get("status") or "pending"),
                "verifier_label": str(item.get("verifier_label") or item.get("verifier") or "未执行"),
                "duration_text": str(item.get("duration_text") or ""),
                "result_items": "；".join(_strings(item.get("result_items"))),
            }
        )
    return tuple(normalized)


def _normalized_links(links: Iterable[Mapping[str, object]]) -> tuple[dict[str, str], ...]:
    normalized: list[dict[str, str]] = []
    for item in links:
        if not isinstance(item, Mapping):
            continue
        label = str(item.get("label") or "").strip()
        href = str(item.get("href") or "").strip()
        if label and href:
            normalized.append({"label": label, "href": href})
    return tuple(normalized)


def _task_headline(task_preview: Mapping[str, object], task_text: str) -> str:
    title = str(task_preview.get("title") or "").strip()
    if title:
        return title
    if task_text:
        return _truncate(task_text, 90)
    return "先写清楚任务，系统才能把整条流程串起来。"


def _decision_headline(mode: str, autogenerated: tuple[str, ...], used_draft_verifier: bool) -> str:
    if autogenerated:
        return "系统先把边界草拟出来，再让你决定要不要覆盖。"
    if used_draft_verifier:
        return "当前先用草稿验收把流程跑通。"
    if mode == "example":
        return "当前直接复用了示例任务的边界和验收方式。"
    return "系统会优先用你给的边界和验收规则。"


def _execution_headline(current_delivery: Mapping[str, object]) -> str:
    context_count = current_delivery.get("context_file_count")
    if context_count:
        return f"当前会把仓库树、{context_count} 个上下文文件和 verifier 一起交给模型。"
    return "当前会把仓库树、任务输入和验收线索一起交给模型。"


def _evidence_headline(context_files: tuple[str, ...], risk_warnings: tuple[str, ...]) -> str:
    if context_files:
        return "首屏只放最关键的上下文和风险信号。"
    if risk_warnings:
        return "当前先暴露最可能影响结果解释的风险。"
    return "当前证据还不多，但结构已经准备好了。"


def _result_status(results: tuple[dict[str, str], ...]) -> str:
    if not results:
        return "pending"
    if any(item["status"] in {"failed", "error"} or item["verifier_label"] == "未通过" for item in results):
        return "failed"
    if all(item["status"] == "succeeded" for item in results):
        return "done"
    return "running"


def _result_headline(results: tuple[dict[str, str], ...], *, used_draft_verifier: bool) -> str:
    if not results:
        return "还没真正运行；现在看到的是可执行草稿。"
    primary = results[0]
    label = primary["profile_label"]
    status_label = primary["status_label"]
    verifier_label = primary["verifier_label"]
    if used_draft_verifier and primary["status"] == "succeeded":
        return f"{label} 已跑完，但结论还是草稿验收视角。"
    return f"{label}：{status_label}，验收{verifier_label}。"


def _result_bullets(results: tuple[dict[str, str], ...], *, used_draft_verifier: bool) -> tuple[str, ...]:
    if not results:
        return _bullets(
            (
                "还没真正执行模型调用，所以还没有真实成败证据。",
                "你现在看到的是任务边界、上下文、验收方式和工作环境草稿。",
                "点运行后，这里会直接给出成败、验收结果和关键证据。",
            )
        )
    primary = results[0]
    summary_items = tuple(
        f"{item['profile_label']}：{item['status_label']}，验收{item['verifier_label']}{('，耗时' + item['duration_text']) if item['duration_text'] else ''}"
        for item in results[:2]
    )
    return _bullets(
        summary_items
        + _bullets((primary["result_items"].split("；")[0] if primary["result_items"] else "",))
        + (("当前是草稿验收视角，最好再补真实 acceptance checks。",) if used_draft_verifier else ())
    )


def _render_prompt_blocks(prompt_preview: Mapping[str, object]) -> str:
    system_prompt = str(prompt_preview.get("system_prompt") or "").strip()
    user_prompt = str(prompt_preview.get("user_prompt") or "").strip()
    if not system_prompt and not user_prompt:
        return '<div class="story-empty">当前没有可展示的 Prompt 预览。</div>'
    parts: list[str] = []
    if system_prompt:
        parts.append(_render_pre_block("System Prompt", system_prompt))
    if user_prompt:
        parts.append(_render_pre_block("User Prompt", user_prompt))
    return "".join(parts)


def _render_pre_block(title: str, text: str) -> str:
    return "".join(
        [
            '<div class="story-pre-block">',
            f'<div class="story-pre-title">{escape(title)}</div>',
            f"<pre>{escape(text)}</pre>",
            "</div>",
        ]
    )


def _render_string_grid(rows: Iterable[tuple[str, str]]) -> str:
    items = [(str(label).strip(), str(value).strip()) for label, value in rows if str(label).strip()]
    if not items:
        return '<div class="story-empty">当前没有额外细节。</div>'
    return "".join(
        [
            '<div class="story-kv-grid">',
            "".join(
                f'<div class="story-kv-row"><span class="story-kv-label">{escape(label)}</span><span class="story-kv-value">{escape(value or "未填写")}</span></div>'
                for label, value in items
            ),
            "</div>",
        ]
    )


def _render_string_list(items: Iterable[str], *, empty_text: str, css_class: str = "story-detail-list") -> str:
    normalized = [str(item).strip() for item in items if str(item).strip()]
    if not normalized:
        return f'<div class="story-empty">{escape(empty_text)}</div>'
    return "".join(
        [
            f'<ul class="{escape(css_class)}">',
            "".join(f"<li>{escape(item)}</li>" for item in normalized),
            "</ul>",
        ]
    )


def _render_link_list(items: Iterable[Mapping[str, str]]) -> str:
    normalized = [(str(item.get("label") or "").strip(), str(item.get("href") or "").strip()) for item in items]
    normalized = [(label, href) for label, href in normalized if label and href]
    if not normalized:
        return '<div class="story-empty">当前还没有可打开的结果链接。</div>'
    return "".join(
        [
            '<div class="story-link-list">',
            "".join(f'<a class="story-link-chip" href="{escape(href)}">{escape(label)}</a>' for label, href in normalized),
            "</div>",
        ]
    )


def _detail_items(items: Iterable[tuple[str, str]]) -> tuple[StoryDetail, ...]:
    details: list[StoryDetail] = []
    for title, body_html in items:
        if str(title).strip() and str(body_html).strip():
            details.append(StoryDetail(str(title), str(body_html)))
    return tuple(details)


def _status_label(status: str) -> str:
    labels = {
        "ready": "已草拟",
        "info": "说明",
        "pending": "待运行",
        "running": "进行中",
        "done": "已完成",
        "failed": "失败",
    }
    return labels.get(status, status)


def _bullets(items: Iterable[str]) -> tuple[str, ...]:
    return tuple(str(item).strip() for item in items if str(item).strip())


def _strings(value: object) -> tuple[str, ...]:
    if value is None:
        return ()
    if isinstance(value, str):
        return (value,) if value.strip() else ()
    if not isinstance(value, Iterable):
        return ()
    return tuple(str(item).strip() for item in value if str(item).strip())


def _mapping(value: object) -> Mapping[str, object]:
    return value if isinstance(value, Mapping) else {}


def _join_items(items: Iterable[str], empty_text: str) -> str:
    normalized = [str(item).strip() for item in items if str(item).strip()]
    return "、".join(normalized[:3]) if normalized else empty_text


def _truncate(text: str, limit: int) -> str:
    normalized = " ".join(str(text).split())
    if len(normalized) <= limit:
        return normalized
    return normalized[: limit - 1].rstrip() + "…"
