from __future__ import annotations

import sys
import unittest
from pathlib import Path


SRC_ROOT = Path(__file__).resolve().parents[2] / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from repo_harness_lab.shared.portal_story import build_portal_story_sections, render_portal_story


class PortalStoryTests(unittest.TestCase):
    def test_preview_story_builds_six_sections(self) -> None:
        preview = {
            "task_spec_preview": {
                "title": "Sync policy docs",
                "description": "Keep notice and checklist aligned.",
                "repo_root": "E:/demo/repo",
                "editable_paths": ["docs", "ops"],
                "expected_changed_files": ["docs/policy_notice.md", "ops/policy_rollout_checklist.md"],
                "behavioral_checks": ["公告和清单必须一致"],
                "verifier_step_names": ["policy-checklist-check"],
            },
            "shared_task_information": {
                "environment": {
                    "repo_source_kind": "local_path",
                    "checkout_mode": "copy",
                    "allow_network": False,
                }
            },
            "current_delivery": {
                "context_file_count": 2,
                "context_files": ["docs/policy_scope.txt", "ops/rollout_notes.md"],
                "tree_file_count": 8,
                "included_input_names": ["policy bundle"],
                "included_verifier_steps": ["policy-checklist-check"],
                "additional_delivery_items": ["Repository tree attached (8 files discoverable, preview shows 8 entries)."],
                "notes": ["Will attach up to 3 context files; current preview selects 2."],
                "prompt_preview": {
                    "system_prompt": "system",
                    "user_prompt": "user",
                },
                "tree_preview": ["docs/policy_notice.md", "ops/policy_rollout_checklist.md"],
            },
            "risk_warnings": ["Verifier plan is narrow, so completion evidence may stay weak."],
            "uplift_readiness": {
                "recommendation_reasons": ["包含 verifier 步骤，结果更容易解释"],
                "declared_harness_signals": ["task_inputs", "verifier_plan"],
            },
        }

        sections = build_portal_story_sections(
            preview=preview,
            form_fields={"repo_path": "E:/demo/repo", "task_text": "Sync policy docs."},
            mode="custom",
            autogenerated_fields=(),
            used_draft_verifier=False,
            results=(),
            links=(),
            detail_blocks=(),
        )

        self.assertEqual([section.key for section in sections], ["task", "decision", "execution", "evidence", "result", "details"])
        self.assertEqual(sections[4].status, "pending")
        self.assertIn("Sync policy docs", sections[0].headline)
        self.assertIn("docs/policy_notice.md", "\n".join(sections[0].bullets))
        self.assertIn("policy-checklist-check", "\n".join(sections[1].bullets))
        self.assertIn("隔离工作区副本", "\n".join(sections[2].bullets))
        self.assertIn("确定性 verifier", "\n".join(sections[2].bullets))
        self.assertIn("docs/policy_scope.txt", "\n".join(sections[3].bullets))
        self.assertIn("官方 scorer", "\n".join(sections[5].bullets))

        html = render_portal_story(sections)
        self.assertIn("任务是什么", html)
        self.assertIn("最终结果是什么", html)
        self.assertIn("story-detail", html)

    def test_run_story_marks_result_section_done(self) -> None:
        sections = build_portal_story_sections(
            preview={},
            form_fields={"task_text": "Update README", "repo_path": "E:/demo/repo"},
            mode="custom",
            autogenerated_fields=("context_paths", "editable_paths"),
            used_draft_verifier=True,
            results=(
                {
                    "profile": "current",
                    "profile_label": "Current package",
                    "status": "failed",
                    "status_label": "失败",
                    "verifier": "failed",
                    "verifier_label": "未通过",
                    "duration_text": "1.20 s",
                    "result_items": ["工作区没有检测到文件改动。"],
                },
            ),
            links=(
                {"label": "运行报告", "href": "/runs/run-001/report.html"},
            ),
            detail_blocks=(),
        )

        self.assertEqual(sections[4].status, "failed")
        self.assertIn("失败", sections[4].headline)
        self.assertIn("工作区没有检测到文件改动。", "\n".join(sections[4].bullets))
        self.assertIn("运行报告", "\n".join(sections[5].bullets))


class ReadmeNarrativeTests(unittest.TestCase):
    def test_english_readme_uses_portal_six_section_story(self) -> None:
        readme = (Path(__file__).resolve().parents[2] / "README.md").read_text(encoding="utf8")

        self.assertIn("## What The Task Is", readme)
        self.assertIn("## How The System Decides This", readme)
        self.assertIn("## How Execution Actually Works", readme)
        self.assertIn("## What Evidence The System Keeps", readme)
        self.assertIn("## What The Current Result Means", readme)
        self.assertIn("## What You Can Inspect Next", readme)

    def test_chinese_readme_mirrors_portal_six_section_story(self) -> None:
        readme = (Path(__file__).resolve().parents[2] / "README.zh-CN.md").read_text(encoding="utf8")

        self.assertIn("## 任务是什么", readme)
        self.assertIn("## 系统怎么决定这样做", readme)
        self.assertIn("## 实际怎么执行", readme)
        self.assertIn("## 拿到了哪些关键证据", readme)
        self.assertIn("## 最终结果是什么", readme)
        self.assertIn("## 还可以往下看什么细节", readme)

    def test_english_readme_references_generated_evidence_images(self) -> None:
        readme = (Path(__file__).resolve().parents[2] / "README.md").read_text(encoding="utf8")

        self.assertIn("docs/assets/readme/swebench-benchmark-demo.png", readme)
        self.assertIn("docs/assets/readme/official-swebench-demo.png", readme)
        self.assertIn("docs/assets/readme/uplift-dashboard-demo.png", readme)

    def test_chinese_readme_references_generated_evidence_images(self) -> None:
        readme = (Path(__file__).resolve().parents[2] / "README.zh-CN.md").read_text(encoding="utf8")

        self.assertIn("docs/assets/readme/swebench-benchmark-demo.png", readme)
        self.assertIn("docs/assets/readme/official-swebench-demo.png", readme)
        self.assertIn("docs/assets/readme/uplift-dashboard-demo.png", readme)
